---
- name: Install software packages
  hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  vars:
    dotfiles_dir: "{{ playbook_dir }}"
    home_dir: "{{ ansible_facts.env.HOME }}"

  tasks:
    - name: Install macOS packages via Homebrew
      include_tasks: roles/dotfiles/tasks/packages_darwin.yml
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Install Mac App Store applications
      include_tasks: roles/dotfiles/tasks/mas.yml
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Install tools with custom installers
      include_tasks: roles/dotfiles/tasks/tool_installers.yml

    - name: Install Go packages
      include_tasks: roles/dotfiles/tasks/go_packages.yml
