---
- name: Set dotfiles secret directory (optional)
  set_fact:
    dotfiles_secret_dir_effective: "{{ dotfiles_secret_dir | default(home_dir ~ '/.dotfiles-secret') }}"
  when:
    - (dotfiles_secret_repo is defined and dotfiles_secret_repo | length > 0) or (dotfiles_secret_dir is defined and dotfiles_secret_dir | length > 0)

- name: Clone or update managed dotfiles secret repo (optional)
  become: no
  git:
    repo: "{{ dotfiles_secret_repo }}"
    dest: "{{ dotfiles_secret_dir_effective }}"
    version: main
    update: yes
    force: yes
  when:
    - dotfiles_secret_repo is defined
    - dotfiles_secret_repo | length > 0
